name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  prettier:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm install

      - name: Check Prettier formatting
        run: npm run prettier

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: prettier # Run this job after 'lint' job is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm install

      - name: Build with tsup
        run: npm run build

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build # Run this job after 'build' job is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm install

      - name: Run Tests with Vitest
        run: npm run test

  deploy:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: test # Run this job after 'test' job is successful
    if: github.ref == 'refs/heads/main' # Only run this job on the 'main' branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm install

      - name: Log in to npm
        uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org/"
          scope: "@your-scope" # Zmień, jeśli masz określony scope na npm

      - name: Publish package to npm
        run: npm publish --access public # Publikuje paczkę na npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Token do logowania na npm (dodaj do Secrets w repo)

